### ISSUE TITLE
Playlist ISSUE

### ISSUE THREAD

**Issue by Vito711** [blackcandy-org/black_candy#123]
When I want to add a song in a playlist,  the site gives me an error " the file is already present in the Playlist" 
This happens when i listen a music, and i want to add another music in the playlist

**Comment by aidewoode** [comment]
Hi, Can you describe in detail how you operate to get this issue? I can't reproduce the issue on my server

**Comment by jaredmoody** [comment]
I'm seeing this issue as well, here's how to reproduce:

1. Start playing a song so that it's added to the Current list
2. Attempt to add that same song to a playlist.
3. Error message displays instead of the song being added to the playlist

**Comment by aidewoode** [comment]
It's wired, after follow the step I still can't reproduce the issue. This error only raised when the playlist already have the song in it.

**Comment by jaredmoody** [comment]
I've spotted the source of this issue - it's due to caching, which is why it's present in production and not in development.

The collection of playlist partials is cached, but the `dialog/playlists/_playlist` partial contains a dynamic `params[:song_id]` value, so the partial will cache the song_id in the partial and always submit the same value after the first submit.

The easiest solution would be to not cache that list of playlist partials, but perhaps a better one would be to wrap them in a form containing the dynamic song_id value and have each playlist partial contain a button that only submits the playlist_id and not the song_id.

I'm out of time tonight, so I can implement this another night, or you can go for it.

**Comment by aidewoode** [comment]
OK, I will take time on this issue, thanks
