### ISSUE TITLE
Setup Instructions Issues

### ISSUE THREAD

**Issue by jaredmoody** [blackcandy-org/black_candy#130]
I'm having some trouble with the setup instructions for development.

Everything went ok until `rails db:setup`, which fails with:

```
rails aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
```

It looks like RAILS_ENV is set to production when I think it should be development?

However, `RAILS_ENV=development rails db:setup` also fails for me:

```
We could not find your database: postgres. Which can be found in the database configuration file located at config/database.yml.

To resolve this issue:

- Did you create the database for this app, or delete it? You may need to create your database.
- Has the database name changed? Check your database.yml config has the correct database name.

To create your database, run:

        bin/rails db:create
Couldn't create 'black_candy_development' database. Please check your configuration.
rails aborted!
ActiveRecord::NoDatabaseError: We could not find your database: postgres. Which can be found in the database configuration file located at config/database.yml
...
Caused by:
PG::ConnectionBad: FATAL:  role "postgres" does not exist
```

Is the nix config out of date here?

**Comment by aidewoode** [comment]
Seems like there is a problem with the environment variable configuration of the dev env. 
What's you get when you print RAILS_ENV environment variable in shell? `echo $RAILS_ENV`.

**Comment by jaredmoody** [comment]
It's `production`. I'm not very familiar with nix, but I don't see this configured in the `shell.nix` file - is it coming from the tarball that `shell.nix` is referencing?

**Comment by aidewoode** [comment]
This shell.nix file doesn't set RAILS_ENV.  Do you set a global  RAILS_ENV  on your environment? When you out the nix shell, what value are you get form RAILS_ENV.  Can you try to run `nix-shell --pure` to see value of  RAILS_ENV environment?

**Comment by jaredmoody** [comment]
>  Do you set a global RAILS_ENV on your environment?

No, I don't, `echo $RAILS_ENV` is blank when I'm not in nix, which is why I thought it was being set by nix somewhere.

`nix-shell --pure` still has RAILS_ENV as production:

```
❯ echo $RAILS_ENV

❯ nix-shell --pure

[nix-shell:~/code/black_candy]$ echo $RAILS_ENV
production
```

**Comment by aidewoode** [comment]
🤔 I have tried to configure the dev environment on a plain nix docker container. The value of RAILS_ENV is correct. It's empty. So I think the RAILS_ENV  issue maybe is caused by your local environment, and nix has nothing to do with it. 

As previously mentioned, you can set rails env on command to avoid the RAILS_ENV issue `RAILS_ENV=development rails db:setup`. But still got error from database. That's because the database wasn't running yet. It's a bit tricky. Because nix-shell can not auto run service, So when you first time to setup database, you should manually run postgres in  nix-shell first, like this `postgres`. Then launch a new terminal instance to run 'RAILS_ENV=development rails db:setup'. When the database setup is complete, now you can stop the running postgres.  Because I have already config the postgres and redis service on Procfile.dev, so you don't have to manually run those services . And use `./bin/dev ` to run those services.

So the thing is when you first time setup database use nix, you should manually run postgres before it.

I should update the nix dev setup Instructions for this.

**Comment by jaredmoody** [comment]
I figured out that I had Postgres running already, which prevented Postgres from starting inside the nix shell. I wasn't clear that the nix environment is not completely separate from the host environment.
