### ISSUE TITLE
Adding a file to a playlist should add it at the end of the playlist

### ISSUE THREAD

**Issue by jaredmoody** [blackcandy-org/black_candy#150]
It seem strange to me that adding a song to a playlist adds it to the top, every player I've seen that I can think of adds it to the bottom.

I can submit a PR to change this if you agree.

**Comment by aidewoode** [comment]
Black candy used to add song at the end of the playlist. The reason that I changed to add song at the top is easier to implement , because I don't need to determine the playlist have next page or not to add the song to the playlist. And I remember Spotify used to have the same behavior. So I change to add song at the top of the playlist.  But now I checked Spotify also changed, So it's fine to change the behavior.
