### ISSUE TITLE
High CPU usage when playing audio

### ISSUE THREAD

**Issue by jaredmoody** [blackcandy-org/black_candy#154]
While listening today, I noticed a stutter every so often in playback, and traced that to very high CPU usage from black candy when playing in Safari

<img width="920" alt="Activity Monitor 2022-03-18 17-14-35" src="https://user-images.githubusercontent.com/27690/159098876-badbcc9e-b9e7-4a66-aa72-fbfdbf68feb4.png">

It is a large file encoded in ALAC, and while I have "Allow transcode lossless" switched on, I'm seeing AAC listed in the safari network pane, so perhaps the transcode is happening on my local machine which is causing the high CPU.

![Settings 2022-03-18 17-20-08](https://user-images.githubusercontent.com/27690/159099071-b64ee74c-1d81-426e-9161-1077604283a8.png)

I don't have this same issue in Jellyfin, my current primary player which I'd like to switch away from, so seems specific to BlackCandy, and when playing in Jellyfin, it looks like it is transcoding to m4a:

![Jellyfin 2022-03-18 17-23-16](https://user-images.githubusercontent.com/27690/159099215-c2875092-8aba-4e4b-b089-b5b009ae9eaa.png)

**Comment by aidewoode** [comment]
ALAC encoded file can stored within an mp4 container with  .m4a filename extension. You know .m4a filename extension can also be used as lossy formate. Black candy just simple use filename extension to check if the formate is lossless or not. So like ALAC encoded file, black candy just treat it as a lossy formate. So there is no transcoding when playing ALAC encoded file. I am not quite   sure why playing ALAC encoded file cause high CPU usage.  This need deeper investigation. It would be great if you can send me the sample file that cause high CPU usage.

**Comment by jaredmoody** [comment]
This one causes it:

https://ln5.sync.com/dl/05b929890#4zzsf9cn-un6mcbsg-e8cdxsba-r3xs88gf

**Comment by aidewoode** [comment]
I got the file. Thanks

**Comment by aidewoode** [comment]
Hi,  I have founded the reason why the high CPU usage when playing audio on safari. It's not because the issue of transcoding. When I was playing  mp3 I still got high CPU usage on safari. On my laptop it's about 50% usage on CPU. Then I've founded that's because I update the DOM of  song playback timer on `window.requestAnimationFrame`, that will cause a lot of repaint on safari therefore high CPU usage. 

But on this issue there is another problem need to be solved. The problem is black candy can not check if the formate is lossless or no when the formate use general container, like mp4 container. And I will create another issue for this problem.
