### ISSUE TITLE
Option to move playlist to the Albums, Artist, etc. bar

### ISSUE THREAD

**Issue by 63427083** [blackcandy-org/black_candy#205]
I've tested black candy for some days now and while i can say do like very much where this project seems to head, i'm a bit irritated by the 'Playlist' tab. Why not move it into the Albums, Artist, etc. bar, or at least give the option to? Playlists could get personal images and wouldn't hide the current playing list when just adding a few songs. 
Greetings

![example](https://user-images.githubusercontent.com/77916527/192656936-7079e01e-189c-4d55-88e5-fa70b621ffbc.png)

**Comment by aidewoode** [comment]
Thanks for your advice. And black candy has already moved playlists from sidebar to new library page on new layout in order to support mobile app. Those changes are still in master branch, I will not release it until the iOS app is ready. So if you want to try the new layout, you can use the edge  docker image `docker pull blackcandy/blackcandy:edge`. The edge image is build base on master branch.

**Comment by 63427083** [comment]
Great to hear if i wasn't the only one who thought it to be obvious. I'll check out the edge version after work.
