### ISSUE TITLE
Deploying to Vercel

### ISSUE THREAD

**Issue by TrapjawwS** [blackcandy-org/black_candy#364]
Hello. I was wondering if deploying to Vercel would be possible. I am a broke beginner, so If it is possible, I was wondering how. I would use something other than Vercel, but I'm broke. Help would be appreciated. Thanks!

**Comment by aidewoode** [comment]
I don't think you can use Vercel to deploy black candy, because Vercel doesn't support Docker deployments. See: https://vercel.com/guides/does-vercel-support-docker-deployments. You can search on internet see if there are some free web hosting service. But I don't recommend you use web hosting service to host black candy, because anyway you maybe still need buy extra disk space to store your music files in case you have a lot of music files and the free plan doesn't have enough disk space to use. Since you are broke,  I think you could use some your own old hardware, like old computer or old android phone to use as a home server to host black candy. you can also use some cheap hardware to use as home server as well, like Raspberry Pi.
